= Addon: Oauth2 Proxy

Adding the `oauth2-proxy` addon will allow you to use the https://github.com/oauth2-proxy/oauth2-proxy[Oauth2 Proxy] to authenticate users using Keycloak or similar Oauth2 providers.

Check the https://oauth2-proxy.github.io/oauth2-proxy/docs/[Oauth2 Proxy docs] for all possible configuration options.

The addon adds the following configuration options under the `INSTANCE.prometheus.config._oauth2Proxy` key:

== `ingress.enabled`

[horizontal]
type:: boolean
default:: `true`

Whether to deploy an ingress for the Oauth2 Proxy.

== `ingress.host`

[horizontal]
type:: string
default:: `null`
example:: `prometheus-infra.example.com`

The hostname of the ingress.

== `ingress.annotations`

[horizontal]
type:: dictionary
default:: `{}`
example::
+
[source,yaml]
----
cert-manager.io/cluster-issuer: letsencrypt-production
----

== `ingress.tls.enabled`

[horizontal]
type:: boolean
default:: `true`

Whether to enable TLS for the ingress.

== `ingress.tls.secretName`

[horizontal]
type:: string
default:: `null`

The name of the secret containing the TLS certificate.
If left empty the name will be generated from the ingress name by appending `-tls`.

== `proxyEnv`

[horizontal]
type:: dictionary
default:: `{}`
example::
+
[source,yaml]
----
OAUTH2_PROXY_COOKIE_SECRET:
  secretKeyRef:
    name: oauth2-proxy
    key: cookieSecret
OAUTH2_PROXY_CLIENT_SECRET:
  secretKeyRef:
    name: oauth2-proxy
    key: clientSecret
----

A dictionary of environment variables to set on the Oauth2 Proxy container.

If given a string, the value will be used as the value of the environment variable.
If given a dictionary, the value will be inserted under the `valueFrom` key.

== `proxyArgs`

[horizontal]
type:: dictionary
default:: `{}`
example::
+
[source,yaml]
----
proxyArgs:
  "email-domain": example.com
  "provider": keycloak-oidc
  "provider-display-name": "Example Account"
  "oidc-issuer-url": https://example.com/auth/realms/example-realm
  "custom-sign-in-logo": https://example.com/_images/logo.png
  "real-client-ip-header": X-Forwarded-For
----

A dictionary of arguments to pass to the Oauth2 Proxy.

== Example

[source,yaml]
----
addons:
  - oauth2-proxy

instances:
  default-instance:
    prometheus:
      enabled: true
      config:
        _oauth2Proxy:
          ingress:
            host: prometheus.example.com
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
          proxyEnv:
            OAUTH2_PROXY_COOKIE_SECRET:
              secretKeyRef:
                name: oauth2-proxy
                key: cookieSecret
            OAUTH2_PROXY_CLIENT_SECRET:
              secretKeyRef:
                name: oauth2-proxy
                key: clientSecret
          proxyArgs:
            "email-domain": example.com
            "provider": keycloak-oidc
            "provider-display-name": "Example Account"
            "oidc-issuer-url": https://example.com/auth/realms/example-realm
            "custom-sign-in-logo": https://example.com/_images/logo.png
            "real-client-ip-header": X-Forwarded-For
----
